version: '3.8'

services:
  app:
    image: order-manager:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-manager
    ports:
      - "8081:80"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/order-manage
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
    networks:
      - order-manage-network

  db:
    image: postgres:16-alpine
    container_name: order-manager-db
    environment:
      - POSTGRES_DB=order-manage
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - order-manage-network

volumes:
  postgres-data:

networks:
  order-manage-network:
    driver: bridge
