server:
  port: 80

spring:
  application:
    name: order-manage
  servlet:
    multipart:
      maxFileSize: 10MB # ?? ??? ?? ??
      maxRequestSize: 30MB  # ? ?? ?? ??? ?? ??
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  profiles:
    active:
      - dev
  config:
    import: optional:file:.env[.properties]
